In [86]:
import re
import numpy as np
file1 = open('sample.txt', 'r') 
Lines = file1.readlines() 
  
# Strips the newline character 
mat=[]
for line in Lines: 
    s = line.replace(".", "-1 ").replace("L","0 ")
    x = np.fromstring(s, dtype=int, sep=' ')
    mat.append(x)
seats=np.array(mat)


def get_around(mat, point):
    adjacency = [(i+point[0],j+point[1]) for i in (-1,0,1) for j in (-1,0,1) if not (i == j == 0)] #the adjacency matrix
    t=[]
    for c in adjacency:
        if (c[0] < mat.shape[0])and( c[1] < mat.shape[1]) and(c[0] > -1)and( c[1] > -1):
            t.append(mat[c[0]][c[1]])
    return np.array(t)
# mat= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# a = get_around(mat,(1,1));

seats_a = np.copy(seats);
seats_b = np.copy(seats);
print(seats)
for l in range(1,100):
    seats_b = np.copy(seats_a)
    for i in range(seats.shape[0]):
        for j in range(seats.shape[1]):
            if (seats_a[i,j]==0):
                around = get_around(seats_a,(i,j));
                occupied= (around ==1).sum()
                if occupied == 0 :
                    seats_b[i,j] = 1;
    seats_a = np.copy(seats_b)
    for i in range(seats.shape[0]):
        for j in range(seats.shape[1]):
            if (seats_b[i,j]>0):
                around = get_around(seats_b,(i,j));
                occupied= (around ==1).sum()
                if occupied >= 4 :
                    seats_a[i,j] = 0;
    if (seats_b==seats_a).all():
        print("Stable!!!");
        break
print(f"Rounds : {l}")        
(seats_b==1).sum()



[[ 0 -1  0  0 -1  0  0 -1  0  0]
 [ 0  0  0  0  0  0  0 -1  0  0]
 [ 0 -1  0 -1  0 -1 -1  0 -1 -1]
 [ 0  0  0  0 -1  0  0 -1  0  0]
 [ 0 -1  0  0 -1  0  0 -1  0  0]
 [ 0 -1  0  0  0  0  0 -1  0  0]
 [-1 -1  0 -1  0 -1 -1 -1 -1 -1]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0 -1  0  0  0  0  0  0 -1  0]
 [ 0 -1  0  0  0  0  0 -1  0  0]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [85]:
a = np.zeros([7,7])
p = (3,4)
a[5,6] =1
a[0,4] =1

a[p]=7

def f0(p,i):
    return (p[0] +i, p[1]+i)
def f1(p,i):
    return (p[0]   , p[1]+i)
def f2(p,i):
    return (p[0] -i, p[1]+i)

def f3(p,i):
    return (p[0] +i, p[1] )
def f4(p,i):
    return (p[0] -i, p[1] )

def f5(p,i):
    return (p[0] +i, p[1] - i)
def f6(p,i):
    return (p[0]   , p[1] - i)
def f7(p,i):
    return (p[0] -i, p[1] - i)


directions=[f0,f1,f2,f3,f4,f5,f6,f7]
L = max(a.shape)
def valid_range(c):
    return (max(c) < L) and(min(c)>=0)
def search(fx,a,p):
    for i in range(1,L):
        c = fx(p,i)
        if valid_range(c):
            x=a[c]
            if (x==1):
                return 1
            elif (x==0):
                return 0
        else:
            break;
    return 0

print(a)
def calc_adj(a,p):
    cnt=0
    for f in directions:
        cnt+=search(f,a,p)
    return cnt


[[0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 7. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [98]:
import re
import numpy as np
file1 = open('input.txt', 'r') 
Lines = file1.readlines() 
  
# Strips the newline character 
mat=[]
for line in Lines: 
    s = line.replace(".", "-1 ").replace("L","0 ")
    x = np.fromstring(s, dtype=int, sep=' ')
    mat.append(x)
seats=np.array(mat)
seats_a = np.copy(seats);
seats_b = np.copy(seats);
occupied_mat = np.zeros(seats.shape)


def f0(p,i):
    return (p[0] +i, p[1]+i)
def f1(p,i):
    return (p[0]   , p[1]+i)
def f2(p,i):
    return (p[0] -i, p[1]+i)

def f3(p,i):
    return (p[0] +i, p[1] )
def f4(p,i):
    return (p[0] -i, p[1] )

def f5(p,i):
    return (p[0] +i, p[1] - i)
def f6(p,i):
    return (p[0]   , p[1] - i)
def f7(p,i):
    return (p[0] -i, p[1] - i)


directions=[f0,f1,f2,f3,f4,f5,f6,f7]
L = max(seats.shape)
def valid_range(c):
    return (min(c)>=0) and (c[0]>seats.shape[0]) and (c[1]>seats.shape[0])
    return 

def search(fx,a,p):
    for i in range(1,L):
        c = fx(p,i)
        if valid_range(c):
            x=a[c]
            if (x==1):
                return 1
            elif (x==0):
                return 0
        else:
            break;
    return 0

def calc_adj(a,p):
    cnt=0
    for f in directions:
        cnt+=search(f,a,p)
    return cnt



for l in range(1,10):
    print(f"==={l}")
    seats_b = np.copy(seats_a)
    for i in range(seats.shape[0]):
        for j in range(seats.shape[1]):
            if (seats_a[i,j]==0):
                occupied= calc_adj(seats_a,(i,j))
                if occupied == 0 :
                    seats_b[i,j] = 1;
    seats_a = np.copy(seats_b)
    print(seats_a)
    
    for i in range(seats.shape[0]):
        for j in range(seats.shape[1]):
            if (seats_b[i,j]>0):
                occupied= calc_adj(seats_b,(i,j))
                occupied_mat[i,j]=occupied;
                if occupied >= 5 :
                    seats_a[i,j] = 0;
    print("Occupied")
    print(occupied_mat)
    print("A")
    print(seats_a)
    print("B")
    print(seats_b)
    
    if (seats_b==seats_a).all():
        print("Stable!!!");
        break
print(f"Rounds : {l}")        

print((seats_b == 1).sum())



===1
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
Occupied
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
A
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
B
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
Stable!!!
Rounds : 1
7195
