In [66]:
import numpy as np

file1 = open('sample.txt', 'r') 
Lines = file1.readlines() 
  
# Strips the newline character 

# Read conditions
cond={}
for i,line in enumerate(Lines): 
    a=line.strip().split(":")
    if len(a)==1:
        your_ticket = np.fromstring(Lines[i+2],sep=',',dtype=int)
        line_others = i+5;
        break
    cond[a[0]] = [ [int (a)for a in c.split('-')] for c in a[1].split(' or ')]
#  Read Your Ticket
print()
    
def is_valid(x,cond):
    for c in cond:
        for r in cond[c]:
            if x>=r[0] and x<=r[1]:
                return True
    return False

is_valid(43,cond)  
print(your_ticket)
others=[]
for line in Lines[line_others:]:
    others.append(list(np.fromstring(line,sep=',',dtype=int)))

bad_numbers=[]
print(others)
for o in others:
    for x in o:
        if not(is_valid(x,cond)):
            bad_numbers.append(x)
print(np.sum(bad_numbers))


[ 7  1 14]
[[7, 3, 47], [40, 4, 50], [55, 2, 20], [38, 6, 12]]
71


In [184]:
import numpy as np
# from collections import OrderedDict 


file1 = open('input.txt', 'r') 
Lines = file1.readlines() 
  
# Strips the newline character 

# Read conditions
cond={}
for i,line in enumerate(Lines): 
    a=line.strip().split(":")
    if len(a)==1:
        your_ticket = np.fromstring(Lines[i+2],sep=',',dtype=int)
        line_others = i+5;
        break
    cond[a[0]] = [ [int (a)for a in c.split('-')] for c in a[1].split(' or ')]
    
def is_valid(x,cond):
    for c in cond:
        for r in cond[c]:
            if x>=r[0] and x<=r[1]:
                return True
    return False

is_valid(43,cond)  

others=[]
for line in Lines[line_others:]:
    others.append(list(np.fromstring(line,sep=',',dtype=int)))

valid_tickets=[]
for o in others:
    v = [ is_valid(x,cond) for x in o]
    if all(v):
        valid_tickets.append(o)
valid_tickets = np.array(valid_tickets)

# print(your_ticket)
# print(valid_tickets)
# print(cond)
C = len(cond)
N = len(valid_tickets)
def is_ok(x,c):
    ranges = list(cond.values())[c] ;
    #print([ranges,x])
    for r in ranges:
        if x>=r[0] and x<=r[1]:
            return True
    return False

possible_list = []
for c0 in range(C):
    mat=np.zeros([C,N], dtype=bool)
    for c1 in range(C):
        for n in range(N):
            mat[c1,n] = is_ok(valid_tickets[n,c1], c0)
    #print(f"----------{list(cond.keys())[c0]}")
    #print(mat)
    #print(mat.all(axis=1))
    possible = (np.argwhere(mat.all(axis=1))).T[0]
    possible_list.append(list(possible))
    #print(possible)

    
    
print("-------------")
possible_dict = {}
for i,l in enumerate(possible_list):
    possible_dict[i] = l;
    print(f"{i} : {l}")
print("-------------")

solution={}
for loop in range(50):
    # Look for Unique
    for k in possible_dict.keys():
        if 1==len(possible_dict[k]):
            solved_col = k;
            allocated_cond = possible_dict[k][0];
            solution[solved_col] =  allocated_cond 
            print(f"Solved for Row {solved_col}, found answer {allocated_cond}")
            break;

    #Exclude found answer from other lists
    for k in possible_dict.keys():
        if allocated_cond in possible_dict[k]:
            possible_dict[k].remove(allocated_cond)
    possible_dict.pop(solved_col)
    if bool(possible_dict):
        pass;
    else:
        print("Solved")
        break;
print(solution)
target = list(cond.keys())[:6]
print(target)
print(your_ticket)
prod=1;
for t in range(6):
    print(your_ticket[solution[t]])
    prod*=your_ticket[solution[t]]
print(f"Answer : {prod}")
    


-------------
0 : [0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 14, 17, 18, 19]
1 : [2, 3, 6, 7, 8, 9, 10, 14, 17, 19]
2 : [2, 3, 6, 7, 8, 9, 10, 14, 17, 18, 19]
3 : [0, 2, 3, 6, 7, 8, 9, 10, 14, 17, 18, 19]
4 : [0, 2, 3, 5, 6, 7, 8, 9, 10, 14, 17, 18, 19]
5 : [0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 14, 17, 18, 19]
6 : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15, 17, 18, 19]
7 : [10]
8 : [2, 3, 6, 7, 9, 10, 14, 17, 19]
9 : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 17, 18, 19]
10 : [2, 6, 7, 9, 10, 14, 17, 19]
11 : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
12 : [2, 6, 10, 14, 19]
13 : [2, 6, 9, 10, 14, 19]
14 : [6, 10, 14]
15 : [2, 6, 7, 9, 10, 14, 19]
16 : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18, 19]
17 : [0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 17, 18, 19]
18 : [2, 6, 10, 14]
19 : [10, 14]
-------------
Solved for Row 7, found answer 10
Solved for Row 19, found answer 14
Solved for Row 14, found answer 6
Solved for Row 18, found answer 2


['departure location', 'departure station', 'departure platform', 'departure track', 'departure date', 'departure time']
[ 73  59  83 127 137 151  71 139  67  53  89  79  61 109 131 103 149  97
 107 101]
137
67
107
73
151
79
855275529001


In [83]:
sudoku = np.zeros([C,C], dtype=int)
for i,idxs in enumerate(possible_list):
    for j in idxs:
        sudoku[j,i]=1;
print(sudoku)    

n_allowed = np.sum(sudoku,axis=0)
row_idx   = np.argwhere(n_allowed==1)[0][0]
cond_idx  = np.argwhere(sudoku[:,row_idx])[0]
print(f"Solved for rows {row_idx} with ans {row_idx}") 
sudoku[cond_idx,:]=0;
print(sudoku)

    


[[0 1 0]
 [1 1 0]
 [1 1 1]]
Solved for rows 2 with ans 2
[[0 1 0]
 [1 1 0]
 [0 0 0]]


In [84]:
possible_list

[[array([1]), array([2])], [array([0]), array([1]), array([2])], [array([2])]]